import type { EffectDefinition, EffectId } from '../types/effects';

export const EFFECT_DEFINITIONS: Record<EffectId, EffectDefinition> = {
  bleeding: {
    id: 'bleeding',
    name: 'Кровотечение',
    icon: '🩸',
    description: 'Персонаж получает 2 урона ПЗ каждый раунд.',
    attackModifier: 0,
    defenseModifier: 0,
    parameterModifiers: {},
    skillModifiers: {},
    damagePerRound: 2,
    durationRounds: null,
    removalConditions: [
      'Первая помощь СЛ 15',
      'Выживание в дикой природе СЛ 15',
    ],
  },
  poisoning: {
    id: 'poisoning',
    name: 'Отравление',
    icon: '☠️',
    description: 'Персонаж получает 3 урона ПЗ каждый раунд.',
    attackModifier: 0,
    defenseModifier: 0,
    parameterModifiers: {},
    skillModifiers: {},
    damagePerRound: 3,
    durationRounds: null,
    removalConditions: ['Стойкость СЛ 15'],
  },
  stunned: {
    id: 'stunned',
    name: 'Ошеломление',
    icon: '💫',
    description: 'Персонаж получает −2 к атаке и защите.',
    attackModifier: -2,
    defenseModifier: -2,
    parameterModifiers: {},
    skillModifiers: {},
    damagePerRound: 0,
    durationRounds: 1,
    removalConditions: ['Автоматически снимается через 1 раунд'],
  },
  blindness: {
    id: 'blindness',
    name: 'Слепота',
    icon: '👁️',
    description:
      'Персонаж получает −3 ко всем атакам и защитам, а также −5 к проверкам Внимания.',
    attackModifier: -3,
    defenseModifier: -3,
    parameterModifiers: {},
    skillModifiers: { Внимание: -5 },
    damagePerRound: 0,
    durationRounds: null,
    removalConditions: ['Особое условие для снятия'],
  },
  intoxication: {
    id: 'intoxication',
    name: 'Опьянение',
    icon: '🍺',
    description:
      'Персонаж получает −2 к Реакции, Ловкости и Интеллекту, а значит и ко всем навыкам этих групп. Существует 25% шанс, что персонаж плохо запомнит события в состоянии опьянения.',
    attackModifier: 0,
    defenseModifier: 0,
    parameterModifiers: { Реа: -2, Лвк: -2, Инт: -2 },
    skillModifiers: {},
    damagePerRound: 0,
    durationRounds: null,
    removalConditions: ['Снимается по истечении времени (на усмотрение мастера)'],
  },
  frozen: {
    id: 'frozen',
    name: 'Замораживание',
    icon: '❄️',
    description:
      'Персонаж получает −3 к Скорости и −1 к Реакции, а значит и ко всем атакам и навыкам Реакции.',
    attackModifier: 0,
    defenseModifier: 0,
    parameterModifiers: { Скор: -3, Реа: -1 },
    skillModifiers: {},
    damagePerRound: 0,
    durationRounds: null,
    removalConditions: ['Сила СЛ 16'],
  },
  burning: {
    id: 'burning',
    name: 'Горение',
    icon: '🔥',
    description:
      'Персонаж получает 5 урона в раунд в охваченные огнём части тела (с учётом множителей: голова ×3, торс ×1, конечности ×0.5). Если броня части тела выше урона — ПЗ не тратится, но теряется 1 ПБ брони.',
    attackModifier: 0,
    defenseModifier: 0,
    parameterModifiers: {},
    skillModifiers: {},
    damagePerRound: 0,
    durationRounds: null,
    removalConditions: ['Потушить огонь (на усмотрение мастера)'],
  },
};

export const ALL_EFFECT_IDS: readonly EffectId[] = [
  'bleeding',
  'poisoning',
  'stunned',
  'blindness',
  'intoxication',
  'frozen',
  'burning',
];
